function L = squircle_length(a)
%SQUIRCLE_LENGTH
%    L = SQUIRCLE_LENGTH(A)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    30-Mar-2022 13:24:21

t2 = cos(t);
t3 = sin(t);
t4 = a.^2;
L = integral(@(t)sqrt(t2.*t3.^2.*t4.*(9.0./4.0)+t2.^2.*t3.*t4.*(9.0./4.0)),0.0,pi./2.0).*4.0;
