function L = super_ellipse_length(a,b)
%SUPER_ELLIPSE_LENGTH
%    L = SUPER_ELLIPSE_LENGTH(A,B)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    28-Mar-2022 14:59:15

t2 = integral(@(t)sqrt(a.^2.*cos(t).^(8.0./3.0).*sin(t).^2.*(4.9e+1./9.0)+b.^2.*cos(t).^2.*sin(t).^(8.0./3.0).*(4.9e+1./9.0)),0.0,pi./2.0);
L = t2.*4.0;
